### ISSUE TITLE
There is no "xtls-rprx-direct" option in the v1.5.3 release?

### ISSUE THREAD

**Issue by Narakuku** [tzmax/V2RayXS#14]
![1](https://user-images.githubusercontent.com/74468372/181012052-354cdfb8-63ea-47b3-b022-57013964882c.png)
![2](https://user-images.githubusercontent.com/74468372/181012055-71641974-73c1-4e1c-89d1-1202a993f3d8.png)

**Comment by tzmax** [comment]
#15
