### ISSUE TITLE
m1pro 无法正常使用vless（包括导入以及手动设置）

### ISSUE THREAD

**Issue by INFWOLAD** [tzmax/V2RayXS#17]
系统版本12.5，使用1.5.4v2rayxs
vless+tcp+xtls
通过vless导入会失败（无法正确识别xtls模式）
尝试手动修改为xtls并修改了advanced中的域名后，依然无法正常连接
尝试更换了最新内核问题依旧。
日志中只有xtls started的输出。
尝试通过socks5连接发现均无法连接。
但是同样vless分享链接在v2rayN（win），qv2ray（mac），shadowrocket（ios）上均识别正常。且其符合规范。
望作者解惑…

**Comment by tzmax** [comment]
@INFWOLAD It may be better if you can stick the log information

**Comment by tzmax** [comment]
same #16
