### ISSUE TITLE
How about the router rather than PAC

### ISSUE THREAD

**Issue by Johnshall** [tzmax/V2RayXS#2]
I think it could be better if we could bypass the dataflow by router rather than PAC.
It's a more "*ray way" to solve this problem and be supported by them, it could also be better to work with proxifier and other software. It's definately a graceful way to solve the traffic loopback.

Thanks for your work! We need you.

**Comment by tzmax** [comment]
@Johnshall You mean ditching the PAC Mode? Are you referring to removing this feature on the client side?

**Comment by tzmax** [comment]
If it is to support the routing function, the function of configuring routing has been implemented before V2RayX. If there is any problem in use, you can describe the problem in detail.

**Comment by Johnshall** [comment]
> @Johnshall You mean ditching the PAC Mode? Are you referring to removing this feature on the client side?

Yes. I think it's useless. I don't think PAC have better performance than router.
