### ISSUE TITLE
订阅链接含有不支持协议导致软件崩溃且无法启动

### ISSUE THREAD

**Issue by mochamapleaf** [tzmax/V2RayXS#23]
请回答下列问题。不按模板发的 issue 将直接被关闭。

0) 如果你没有遇到任何错误和不正常，请在此处回答你想发表的内容：

1) 你正在使用哪个版本的 V2RayXS，你的 macOS 系统版本？
V2RayXS: v1.5.5(beta2)
MacOS: v12.6 (Apple M2)

2) 如果你在操作 V2RayXS 的时候遇到程序崩溃/无反应，请描述你的操作，之后在命令行（终端.app）里运行`/Applications/V2RayXS.app/Contents/MacOS/V2RayXS`，重复上述操作直至软件崩溃，把终端里的输出贴到下面指定的地方。
第一次打开后配置了一个订阅链接，保存后V2RayXS闪退，同时任务栏图标消失，并且无法再次启动
怀疑订阅链接中含有V2rayXS不支持的config （确实有一个Trojan协议的链接）

```
$ /Applications/V2RayXS.app/Contents/MacOS/V2RayXS 
[INFO] GCDWebServer started on port 8070 and reachable at http://192.168.24.103:8070/
2022-12-27 14:50:12.734 V2RayXS[1762:14656] pac file is switched to pac.js
Assertion failed: (decodedString != nil), function +[ConfigImporter decodeBase64String:], file ConfigImporter.m, line 24.
zsh: abort      /Applications/V2RayXS.app/Contents/MacOS/V2RayXS
```

**Comment by tzmax** [comment]
@mochamapleaf Thank you for your feedback, I am preparing to optimize the subscription function. This problem will enter my work list. I hope that after completion, I can invite you to participate in the test
