### ISSUE TITLE
导入机场订阅链接之后，节点名称显示异常

### ISSUE THREAD

**Issue by CometYZ** [tzmax/V2RayXS#24]
1) 你正在使用哪个版本的 V2RayXS，你的 macOS 系统版本？
V2RayXS: v1.5.5(beta2)
macos 13.1

3) 如果 V2RayXS 没有发生崩溃，但是有一些不正常行为，比如上次勾选了 mux，再次打开，mux 的钩没有了。请描述你遇到的不正常行为：
导入机场的订阅链接之后，节点名称显示异常
https://imgur.com/a/vVxHfk3

**Comment by tzmax** [comment]
@CometYZ Thank you for your feedback, I am preparing to optimize the subscription function. This problem will enter my work list. I hope that after completion, I can invite you to participate in the test
