### ISSUE TITLE
mac 睡眠之后唤醒都要重启一下 V2RayXS 才能正常代理, 否则一直提示一直加载中 

### ISSUE THREAD

**Issue by wangz-code** [tzmax/V2RayXS#25]
MacBook Air (M1, 2020)   macOS Monterey  版本 12.5 (21G72)

V2RayXS  版本1.5.4 (2)

睡眠唤醒后  (合上盖子大概半个小时左右) 
直接访问百度 www.baidu.com  能正常打开  (可以排除网络问题)
当访问谷歌 www.google.com  一直处在加载中

目前的办法是
  重启 V2RayXS 或者 重启 wifi   
  
我身边没有其他的m1 可以对照, 不确定上述问题是否只有我会出现,   你们有类似的情况吗?

**Comment by tzmax** [comment]
@wangz-code You can turn on the log in the configuration as debug, try to reproduce the problem again, then export the log information (remember to delete sensitive personal information) and reply to this issue, let me analyze it

**Comment by wangz-code** [comment]
我尝试 是锁定屏幕能百分百复现
  lock screen   100%   Reoccurrence

`

2023/01/29 10:14:57 [Debug] app/log: Logger started
2023/01/29 10:14:57 [Info] app/dns: DNS: created localhost client
2023/01/29 10:14:57 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:1081
2023/01/29 10:14:57 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:8001
2023/01/29 10:14:57 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1081
2023/01/29 10:14:57 [Info] transport/internet/udp: listening UDP on 127.0.0.1:1081
2023/01/29 10:14:57 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:8001
2023/01/29 10:14:57 [Warning] core: Xray 1.5.5 started
2023/01/29 10:14:58 [Info] [3041305092] proxy/socks: TCP Connect request to tcp:alive.github.com:443
2023/01/29 10:14:58 [Info] [3041305092] app/dispatcher: taking detour [xtls] for [tcp:alive.github.com:443]
2023/01/29 10:14:58 [Info] [3041305092] transport/internet/tcp: dialing TCP to tcp:example.com:443
2023/01/29 10:14:58 [Debug] transport/internet: dialing to tcp:example.com:443
2023/01/29 10:14:58 [Info] [3041305092] proxy/vless/outbound: tunneling request to tcp:alive.github.com:443 via example.com:443
2023/01/29 10:15:00 [Debug] app/log: Logger closing
2023/01/29 10:15:02 [Debug] app/log: Logger started
2023/01/29 10:15:02 [Info] app/dns: DNS: created localhost client
2023/01/29 10:15:02 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:1081
2023/01/29 10:15:02 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:8001
2023/01/29 10:15:02 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1081
2023/01/29 10:15:02 [Info] transport/internet/udp: listening UDP on 127.0.0.1:1081
2023/01/29 10:15:02 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:8001
2023/01/29 10:15:02 [Warning] core: Xray 1.5.5 started
2023/01/29 10:16:27 [Info] [2176054349] proxy/socks: TCP Connect request to tcp:www.google.com:443
2023/01/29 10:16:27 [Info] [2176054349] app/dispatcher: taking detour [xtls] for [tcp:www.google.com:443]
2023/01/29 10:16:27 [Info] [2176054349] transport/internet/tcp: dialing TCP to tcp:example.com:443
2023/01/29 10:16:27 [Debug] transport/internet: dialing to tcp:example.com:443
2023/01/29 10:16:28 [Info] [2176054349] proxy/vless/outbound: tunneling request to tcp:www.google.com:443 via example.com:443
2023/01/29 10:17:15 [Info] [3935981955] proxy/socks: TCP Connect request to tcp:safebrowsing.googleapis.com:443
2023/01/29 10:17:15 [Info] [3935981955] app/dispatcher: taking detour [xtls] for [tcp:safebrowsing.googleapis.com:443]
2023/01/29 10:17:15 [Info] [3935981955] transport/internet/tcp: dialing TCP to tcp:example.com:443
2023/01/29 10:17:15 [Debug] transport/internet: dialing to tcp:example.com:443
2023/01/29 10:17:15 [Info] [3935981955] proxy/vless/outbound: tunneling request to tcp:safebrowsing.googleapis.com:443 via example.com:443
2023/01/29 10:17:54 [Info] [814329882] proxy/socks: TCP Connect request to tcp:clients4.google.com:443
2023/01/29 10:17:54 [Info] [814329882] app/dispatcher: taking detour [xtls] for [tcp:clients4.google.com:443]
2023/01/29 10:17:54 [Info] [814329882] transport/internet/tcp: dialing TCP to tcp:example.com:443
2023/01/29 10:17:54 [Debug] transport/internet: dialing to tcp:example.com:443
2023/01/29 10:17:55 [Info] [814329882] proxy/vless/outbound: tunneling request to tcp:clients4.google.com:443 via example.com:443
2023/01/29 10:19:00 [Info] [1367715371] proxy/socks: TCP Connect request to tcp:play.google.com:443
2023/01/29 10:19:00 [Info] [1367715371] app/dispatcher: taking detour [xtls] for [tcp:play.google.com:443]
2023/01/29 10:19:00 [Info] [1367715371] transport/internet/tcp: dialing TCP to tcp:example.com:443
2023/01/29 10:19:00 [Debug] transport/internet: dialing to tcp:example.com:443
2023/01/29 10:19:00 [Info] [1367715371] proxy/vless/outbound: tunneling request to tcp:play.google.com:443 via example.com:443
2023/01/29 10:19:22 [Info] [660935150] proxy/socks: TCP Connect request to tcp:ogs.google.com:443
2023/01/29 10:19:22 [Info] [660935150] app/dispatcher: taking detour [xtls] for [tcp:ogs.google.com:443]
2023/01/29 10:19:22 [Info] [660935150] transport/internet/tcp: dialing TCP to tcp:example.com:443
2023/01/29 10:19:22 [Debug] transport/internet: dialing to tcp:example.com:443
2023/01/29 10:19:22 [Info] [660935150] proxy/vless/outbound: tunneling request to tcp:ogs.google.com:443 via example.com:443
2023/01/29 10:20:17 [Info] [826628852] proxy/socks: TCP Connect request to tcp:www.youtube.com:443
2023/01/29 10:20:17 [Info] [826628852] app/dispatcher: taking detour [xtls] for [tcp:www.youtube.com:443]
2023/01/29 10:20:17 [Info] [826628852] transport/internet/tcp: dialing TCP to tcp:example.com:443
2023/01/29 10:20:17 [Debug] transport/internet: dialing to tcp:example.com:443
2023/01/29 10:20:17 [Info] [826628852] proxy/vless/outbound: tunneling request to tcp:www.youtube.com:443 via example.com:443
2023/01/29 10:20:31 [Info] [2572805922] proxy/socks: TCP Connect request to tcp:i.ytimg.com:443
2023/01/29 10:20:31 [Info] [2572805922] app/dispatcher: taking detour [xtls] for [tcp:i.ytimg.com:443]
2023/01/29 10:20:31 [Info] [2572805922] transport/internet/tcp: dialing TCP to tcp:example.com:443
2023/01/29 10:20:31 [Debug] transport/internet: dialing to tcp:example.com:443
2023/01/29 10:20:31 [Info] [2572805922] proxy/vless/outbound: tunneling request to tcp:i.ytimg.com:443 via example.com:443
2023/01/29 10:21:46 [Info] [3935981955] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
2023/01/29 10:21:46 [Info] [3935981955] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > context canceled
2023/01/29 10:21:56 [Info] [814329882] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
2023/01/29 10:21:56 [Info] [814329882] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > context canceled
2023/01/29 10:23:01 [Info] [1367715371] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
2023/01/29 10:23:01 [Info] [1367715371] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > context canceled
2023/01/29 10:23:24 [Info] [660935150] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
2023/01/29 10:23:24 [Info] [660935150] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > context canceled
2023/01/29 10:24:18 [Info] [826628852] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
2023/01/29 10:24:18 [Info] [826628852] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > context canceled
2023/01/29 10:24:33 [Info] [2572805922] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
2023/01/29 10:24:33 [Info] [2572805922] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > context canceled



`

**Comment by wangz-code** [comment]
可能是我本机某些软件冲突了, 能用就行  作为白嫖党 感谢大佬免费的客户端   

It may be that some software on my computer is in conflict, so I can use it as a free client for the white whoring party to thank the mogul
