### ISSUE TITLE
What does "Use All" mean in Server menu?

### ISSUE THREAD

**Issue by leohougmail** [tzmax/V2RayXS#29]
0) 如果你没有遇到任何错误和不正常，请在此处回答你想发表的内容：

At the bottom of server menu, there is a "Use All" item. Is it a load-balancer or auto-select-first-available server? 

Thanks. Loved your software.

**Comment by tzmax** [comment]
@leohougmail I think this might be something you want to know about https://github.com/tzmax/V2RayXS/blob/master/V2RayX/AppDelegate.m#L993

**Comment by livingfree2023** [comment]
> @leohougmail I think this might be something you want to know about https://github.com/tzmax/V2RayXS/blob/master/V2RayX/AppDelegate.m#L993


Thanks. I got it. It seems V2RayXS is probably the first X-ray client to have this feature. I've never seen that in other clients on MacOS/Android. 

For others who might be interested, I studied https://xtls.github.io/config/routing.html#balancerobject and check the outbound access.log. The server selection seems to be completely random.
