### ISSUE TITLE
Can we please have a VPN mode?

### ISSUE THREAD

**Issue by livingfree2023** [tzmax/V2RayXS#30]
Can we have a VPN mode in the MacOS client? I want to use the tunnel for app that does not support sock/http proxies. (There is such a feature in Nekoray but I couldn't get it work properly with XTLS-Vision)

**Comment by tzmax** [comment]
@livingfree2023 I think what you want is tun mode, please refer to <https://github.com/tzmax/V2RayXS#what-is-tun-mode-experimental>

**Comment by livingfree2023** [comment]
Great. I found it not working 100% of the time. But when it works, it works very well
