### ISSUE TITLE
UI color issues under Dark mode

### ISSUE THREAD

**Issue by Lorilandly** [tzmax/V2RayXS#36]
1. 你正在使用哪个版本的 V2RayXS，你的 macOS 系统版本？
 macOS Monterey Version 12.5
 V2RayXS Version 1.5.6(2)

2. Issue
 Bad UI coloring scheme makes text hard to see

3. Steps to replicate
 Configure -> Advanced -> Rules -> [Select one of the rules] -> Edit list

4. Image
 ![Screen Shot 2023-03-03 at 12 37 23](https://user-images.githubusercontent.com/59900828/222632544-da606d7c-a202-48b6-9045-ddf6f7ccdd1a.jpg)

5. Solution
 Consider making the color of the text white

**Comment by tzmax** [comment]
@Lorilandly you are invited to join the v1.5.7 beta, If there is a problem, let us keep in touch

**Comment by Lorilandly** [comment]
Close as fixed with v1.5.7

![Screen Shot 2023-06-29 at 12 41 02 PM](https://github.com/tzmax/V2RayXS/assets/59900828/1a51486a-e6b0-4e0c-8835-80edeb8e1144)
