### ISSUE TITLE
无法从 VLESS 分享链接导入 vision 流控字段

### ISSUE THREAD

**Issue by ghost** [tzmax/V2RayXS#64]
请回答下列问题。不按模板发的 issue 将直接被关闭。

0) 如果你没有遇到任何错误和不正常，请在此处回答你想发表的内容：

最新的 1.5.9 版本在通过剪贴板导入 (VLESS link) 时，并未同时导入分享链带的 vision 流控参数/字段，例如：

vless://UUID@domain:port?encryption=none&**flow=xtls-rprx-vision**&security=tls&sni=domain&type=tcp&headerType=none#REMARK

通过 VLESS link 导入之后，flow 一项将置空，需要手动再从下拉菜单中选择 xtls-rprx-vision。

请考虑调整这项行为~

**Comment by tzmax** [comment]
The configuration flow is invalid when security is tls, It should be necessary to configure security as xtls
