### ISSUE TITLE
请问下.如何过滤本地局域网的域名

### ISSUE THREAD

**Issue by Erc089** [tzmax/V2RayXS#66]
我 mamp 搭建了本地站点..可能有几十个..我怎么让本地的网站能直接访问呢...

**Comment by tzmax** [comment]
@Erc089 I may not understand your needs very well, but if you need to configure direct connection rules, you can try adding your domain or ip in 'Advanced' -> 'Rules', and then you can enable or disable this routing rule in the menu.
