### ISSUE TITLE
A problem about AppDelegate/getV2rayPath method

### ISSUE THREAD

**Issue by hulixia1992** [tzmax/V2RayXS#9]
https://github.com/tzmax/V2RayXS/blob/1e71a983ae4d1d0ddf69db578e9bc1da7597dd39/V2RayX/AppDelegate.m#L1004-L1010

这里为什么要判断 `v2ray`, `v2ctl` 文件是否存在？难道不应该判断 `xray` 文件是否存在就可以了吗？

**Comment by tzmax** [comment]
@hulixia1992 Oh, this was a mistake of mine, can you submit a PR to help me fix it?
